### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by simo222** [mkimuram/k8sviz#17]
hi,
I get this error for only one namespace.  
any idea what could be the cause. 
my shell script  which is loop through all namespaces is exiting because of this error.    (my shell script has this: set -o errexit)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1157149]

goroutine 1 [running]:
main.toDot(0x7ffd844c7f21, 0xc, 0xc00018de88, 0x3)
	/src/k8sviz.go:388 +0x1049
main.plotDotFile(0x7ffd844c7f21, 0xc, 0x7ffd844c7f38, 0x37, 0x7ffd844c7f31, 0x3, 0xc00006c6ef, 0xc00004c800)
	/src/k8sviz.go:264 +0x11d
main.main()
	/src/k8sviz.go:241 +0x95

**Comment by mkimuram** [comment]
@simo222

Thank you for reporting this bug. 
#18 should fix this issue and I've pushed the fixed version of the image as `mkimuram/k8sviz:devel`.

Could you try testing below?

1. re-download k8sviz.sh:
```
$ curl -LO https://raw.githubusercontent.com/mkimuram/k8sviz/master/k8sviz.sh
$ chmod u+x k8sviz.sh
```

2. delete all existing k8sviz containers (Confirm that no important container exists in the output, before acutally delete them.)
```
$ docker ps -a | grep k8sviz
$ docker ps -a | grep k8sviz | awk '!/^CONTAINER/{print $1}' | xargs docker stop
$ docker ps | grep k8sviz
$ docker ps | grep k8sviz | awk '!/^CONTAINER/{print $1}' | xargs docker rm
```

3. delete current k8sviz container image:
```
$ docker rmi mkimuram/k8sviz:0.2
```

4. try `./k8sviz.sh` with `mkimuram/k8sviz:devel` image by specifying `-i mkimuram/k8sviz:devel` option?

**Comment by simo222** [comment]
just did a new run. still same error. 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1157149]

goroutine 1 [running]:
main.toDot(0x7ffcee51bf04, 0xc, 0xc000207e88, 0x3)
        /src/k8sviz.go:388 +0x1049
main.plotDotFile(0x7ffcee51bf04, 0xc, 0x7ffcee51bf1b, 0x37, 0x7ffcee51bf14, 0x3, 0xc000000180, 0x300000002)
        /src/k8sviz.go:264 +0x11d
main.main()

**Comment by mkimuram** [comment]
It looks like the script is using the old image. Could you run `docker pull mkimuram/k8sviz:devel` and try again with `-i mkimuram/k8sviz:devel` option?

**Comment by simo222** [comment]
Hi

Due to network restrictions, we are not allowed to use non official container images. So basically I am cresting a custum dockerfile. Unfortunately I cannot test this. If you can add extra logging I can create a new container again and try. Unfortunately I am a sys admin and not a developer to debug issue.

**Comment by mkimuram** [comment]
@simo222 

Thank you for explaining your situation.

I've merged the fix. So, in the latest `k8sviz.sh`, the problem should be fixed.

If you need to build your own docker image, you can do it by cloning the current master branch and run 
```
DEVEL_IMAGE=mkimuram/k8sviz DEVEL_TAG=0.3 make image-build
```
Then, you don't need to pull image from docker hub.

**Comment by simo222** [comment]
Thanks. Issue solves
