### ISSUE TITLE
Invoke script without being in script's directory

### ISSUE THREAD

**Issue by chicken231** [mkimuram/k8sviz#2]
Great tool!

It'd be a bit more easy for me to use the script if I didn't have to be in the directory containing the script, as the path to the icons is hard-coded to be relative to `pwd`.

**Comment by mkimuram** [comment]
@chicken231 
 
Thank you for your feedback. I hope above PR fixes this.

Could you check if it works as expected? Then I will merge it to master branch.

**Comment by chicken231** [comment]
It's working as expected - thanks!

**Comment by mkimuram** [comment]
Merged. Thank you!
