### ISSUE TITLE
kubernetes 1.22 - changes in ingress prevent generation of output

### ISSUE THREAD

**Issue by skaffille** [mkimuram/k8sviz#37]
Executing k8sviz for a kubernetes 1.22 cluster results in the following error

```
Failed to get k8s resources: failed to get ingresses in namespace "default": the server could not find the requested resource (get ingresses.extensions)
```

https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

API removals for Kubernetes v1.22 
The v1.22 release will stop serving the API versions we've listed immediately below. These are all beta APIs that were previously deprecated in favor of newer and more stable API versions.
 - [...]
 - All beta Ingress APIs (the extensions/v1beta1 and networking.k8s.io/v1beta1 API versions)

**Comment by mkimuram** [comment]
@skaffille 

Thank you for reporting the issue.
I will update client-go.

**Comment by mkimuram** [comment]
@skaffille

PR #38 should fix this issue. I've pushed its version of image as `mkimuram/k8sviz:0.3.3`.

Could you try with `-i mkimuram/k8sviz:0.3.3` option?
(Once the PR is merged, k8sviz.sh will automatically use the version of image. Therefore, this option won't be needed after  it is merged).

**Comment by mkimuram** [comment]
The PR is merged. Please feel free to reopen if there are anything missing or it doesn't work as expected.
