### ISSUE TITLE
Error finding cronjobs

### ISSUE THREAD

**Issue by mattrcampbell** [mkimuram/k8sviz#40]
No matter what namespace I try, I always get the following error:

`$ bin/k8sviz -n default

Failed to get k8s resources: failed to get cronjobs in namespace "default": the server could not find the requested resource
`

**Comment by mkimuram** [comment]
@mattrcampbell 

Thank you for your bug report.

Which version of k8s, are you using?
I suspect that you are using 1.20 or earlier, where cronjob doesn't become [GA](https://kubernetes.io/blog/2021/04/09/kubernetes-release-1.21-cronjob-ga/), yet.

In [this commit](https://github.com/mkimuram/k8sviz/pull/34), I've added CronJob support with batch v1beta1 API as k8sviz version 0.3.2.
And, in [this commit](https://github.com/mkimuram/k8sviz/pull/38), I updated its API to v1 API as k8sviz version 0.3.3, which is the latest version.
Therefore, if you are using 1.20 or earlier, could you try with `-i mkimuram/k8sviz:0.3.2` option, to see if it works?

**Comment by mkimuram** [comment]
Oh, you're directly using binary version that you built by yourself. 
Then, could you rebuild with the da6e68a69672a764424c1abe828940f2adfd8ef7 commit and try with it?

**Comment by mattrcampbell** [comment]
You are correct, the cluster in question is 1.19.  I tried the commit you referenced and that solves the issue!  Thank you.

**Comment by mkimuram** [comment]
Thank you for reporting the test result.
I've added error messages for supported version and version compatibility matrix in README, according to your feedback. 

Please feel free to reopen this issue or create another issue, if there are still anything to improve.
