### ISSUE TITLE
Reflect tags on repository

### ISSUE THREAD

**Issue by els-ipatel** [mkimuram/k8sviz#45]
It seems the current approach to tracking release tags is based on the docker images, can the same tags be reflected on the repository? This helps those that are building a binary and need to reference a specific release.

**Comment by mkimuram** [comment]
Thank you for your suggestion. I've added tags from 0.3.1 to 0.3.4 and will follow this way for later versions.

**Comment by els-ipatel** [comment]
Thank you for the quick response and action on this!
