### ISSUE TITLE
Format: "png" not recognized

### ISSUE THREAD

**Issue by loganmzz** [mkimuram/k8sviz#7]
### Actual behaviour

Input: `./k8sviz.sh -n myproject -t png -o default.png`

Output:

```
Format: "png" not recognized. Use one of:

```

### Expected behaviour

One of :

1. Print supported types
1. Just works :)

### Configuration

* OS : `Windows 10 Enterprise (1909)`

* `uname -a`
```
MINGW64_NT-10.0-18363 18T291 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys
```

* `bash --version`

```
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

* `dot -V`

```
dot - graphviz version 2.43.20200408.0903 (20200408.0903)
```

**Comment by mkimuram** [comment]
Thank you for your feedback.

I'm afraid that the log came from dot command, not from the script.
And as the below URL shows, it seems that the installation of dot command isn't properly done in your environment. (It is for ubuntu, but I guess the message shows that no format is available for the dot command.)
https://bugs.launchpad.net/ubuntu/+source/graphviz/+bug/1289063

Could you install dot command properly and try the script again?
(I don't have windows environment, so I can't test it right now.)

**Comment by loganmzz** [comment]
OK thanks for the information ! I just followed setup quickly, post result after first command as I don't have any info I just posted error here. I will investigate on `dot` then. Thank you for your help !
